///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductListModelData {
  int? id;
  String? slug;
  String? title;
  String? description;
  int? price;
  String? featuredImage;
  String? status;
  String? createdAt;
  bool isSelected = false;

  ProductListModelData(
      {this.id,
      this.slug,
      this.title,
      this.description,
      this.price,
      this.featuredImage,
      this.status,
      this.createdAt,
      this.isSelected = false});

  ProductListModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    slug = json['slug']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toInt();
    featuredImage = json['featured_image']?.toString();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    isSelected = json['isSelected'] ?? false;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['slug'] = slug;
    data['title'] = title;
    data['description'] = description;
    data['price'] = price;
    data['featured_image'] = featuredImage;
    data['status'] = status;
    data['created_at'] = createdAt;
    return data;
  }
}

class ProductListModel {
  int? status;
  String? message;
  int? totalRecord;
  int? totalPage;
  List<ProductListModelData?>? data;

  ProductListModel({
    this.status,
    this.message,
    this.totalRecord,
    this.totalPage,
    this.data,
  });

  ProductListModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    totalRecord = json['totalRecord']?.toInt();
    totalPage = json['totalPage']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProductListModelData>[];
      v.forEach((v) {
        arr0.add(ProductListModelData.fromJson(v));
      });
      data = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['totalRecord'] = totalRecord;
    data['totalPage'] = totalPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
